version: '3.1'
services:
  proxy:
    image: gaetancollaud/serial-ws-proxy
#    container_name: serial-ws-proxy
    build: .
    ports:
      - 1234:8080
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
